DROP TABLE IF EXISTS compilation_events;
DROP TABLE IF EXISTS participation_requests;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS compilations;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS users;


CREATE TABLE IF NOT EXISTS categories (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 0 MINVALUE 0) PRIMARY KEY,
    name            VARCHAR(50) NOT NULL,
    CONSTRAINT categories_name_unique UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 0 MINVALUE 0) PRIMARY KEY,
    name            VARCHAR(250) NOT NULL,
    email           VARCHAR(254) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS locations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 0 MINVALUE 0) PRIMARY KEY,
    lat         FLOAT NOT NULL,
    lon         FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 0 MINVALUE 0) PRIMARY KEY,
    annotation              VARCHAR(2000) NOT NULL,
    category_id             BIGINT,
    created_on              TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description             VARCHAR(7000) NOT NULL,
    event_date              TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id            BIGINT,
    location_id             BIGINT,
    paid                    BOOLEAN,
    participant_limit       INTEGER,
    published_on            TIMESTAMP WITHOUT TIME ZONE,
    request_moderation      BOOLEAN,
    state                   VARCHAR(100) NOT NULL,
    title                   VARCHAR(120) NOT NULL,
    CONSTRAINT fk_events_to_categories FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT fk_events_to_users FOREIGN KEY (initiator_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_events_to_locations FOREIGN KEY (location_id) REFERENCES locations(id)
);

CREATE INDEX idx_events_category_id ON events (category_id);
CREATE INDEX idx_events_initiator_id ON events (initiator_id);
CREATE INDEX idx_events_location_id ON events (location_id);

CREATE TABLE IF NOT EXISTS compilations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 0 MINVALUE 0) PRIMARY KEY,
    pinned          BOOLEAN NOT NULL,
    title           VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS participation_requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 0 MINVALUE 0) PRIMARY KEY,
    created         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id        BIGINT,
    requester_id    BIGINT,
    status          VARCHAR(100) NOT NULL,
    CONSTRAINT fk_participation_requests_to_users FOREIGN KEY (requester_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_participation_requests_to_events FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    CONSTRAINT unique_user_event_request UNIQUE (event_id, requester_id)
);

CREATE INDEX idx_participation_requests_requester_id ON participation_requests (requester_id);
CREATE INDEX idx_participation_requests_event_id ON participation_requests (event_id);

CREATE TABLE IF NOT EXISTS compilation_events (
    compilation_id      BIGINT NOT NULL,
    event_id            BIGINT NOT NULL,
    CONSTRAINT fk_compilation_events_to_compilations FOREIGN KEY (compilation_id) REFERENCES compilations(id),
    CONSTRAINT fk_compilation_events_to_events FOREIGN KEY (event_id) REFERENCES events(id)
);

CREATE TABLE IF NOT EXISTS comments (
    id              BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 0 MINVALUE 0) PRIMARY KEY,
    text            VARCHAR(2000) NOT NULL,
    event_id        BIGINT NOT NULL,
    author_id       BIGINT NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status          VARCHAR(100) NOT NULL,
    CONSTRAINT fk_comments_to_events FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_to_users FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_comments_event_id ON comments (event_id);
CREATE INDEX idx_comments_author_id ON comments (author_id);