DROP TABLE IF EXISTS categories;


CREATE TABLE IF NOT EXISTS categories (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 0 MINVALUE 0) PRIMARY KEY,
    name            VARCHAR(50) NOT NULL,
    CONSTRAINT categories_name_unique UNIQUE (name)
);