services:
  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-db-pg
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres/ewm-stats:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=statistics
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  user-service-db:
    image: postgres:16.1
    container_name: user-service-db-pg
    ports:
      - "6433:5432"
    volumes:
      - ./volumes/postgres/user-service:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - POSTGRES_DB=user
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  event-service-db:
    image: postgres:16.1
    container_name: event-service-db-pg
    ports:
      - "6434:5432"
    volumes:
      - ./volumes/postgres/event-service:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - POSTGRES_DB=event
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  participation-service-db:
    image: postgres:16.1
    container_name: participation-service-db-pg
    ports:
      - "6435:5432"
    volumes:
      - ./volumes/postgres/participation-service:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - POSTGRES_DB=participation
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  comment-service-db:
    image: postgres:16.1
    container_name: comment-service-db-pg
    ports:
      - "6436:5432"
    volumes:
      - ./volumes/postgres/comment-service:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - POSTGRES_DB=comment
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  category-service-db:
    image: postgres:16.1
    container_name: category-service-db-pg
    ports:
      - "6437:5432"
    volumes:
      - ./volumes/postgres/category-service:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - POSTGRES_DB=category
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10