services:
  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-db-pg
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres/ewm-stats:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=statistics
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-db:
    image: postgres:16.1
    container_name: ewm-main-db-pg
    ports:
      - "6432:5432"
    volumes:
      - ./volumes/postgres/ewm-main:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - POSTGRES_DB=main
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
