DROP TABLE IF EXISTS endpoint_hit;

CREATE TABLE IF NOT EXISTS endpoint_hit (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app             varchar(512) NOT NULL,
    uri             varchar(2028) NOT NULL,
    ip              varchar(64) NOT NULL,
    "timestamp"     TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX idx_endpoint_hit_timestamp ON endpoint_hit (timestamp);
CREATE INDEX idx_endpoint_hit_uri ON endpoint_hit (uri);
CREATE INDEX idx_endpoint_hit_ip ON endpoint_hit (ip);