DROP TABLE IF EXISTS participation_requests;


CREATE TABLE IF NOT EXISTS participation_requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 0 MINVALUE 0) PRIMARY KEY,
    created         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id        BIGINT,
    requester_id    BIGINT,
    status          VARCHAR(100) NOT NULL
);

CREATE INDEX idx_participation_requests_requester_id ON participation_requests (requester_id);
CREATE INDEX idx_participation_requests_event_id ON participation_requests (event_id);