DROP TABLE IF EXISTS compilation_events;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS compilations;
DROP TABLE IF EXISTS locations;


CREATE TABLE IF NOT EXISTS locations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 0 MINVALUE 0) PRIMARY KEY,
    lat         FLOAT NOT NULL,
    lon         FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 0 MINVALUE 0) PRIMARY KEY,
    annotation              VARCHAR(2000) NOT NULL,
    category_id             BIGINT,
    created_on              TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description             VARCHAR(7000) NOT NULL,
    event_date              TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id            BIGINT,
    location_id             BIGINT,
    paid                    BOOLEAN,
    participant_limit       INTEGER,
    published_on            TIMESTAMP WITHOUT TIME ZONE,
    request_moderation      BOOLEAN,
    state                   VARCHAR(100) NOT NULL,
    title                   VARCHAR(120) NOT NULL,
    CONSTRAINT fk_events_to_locations FOREIGN KEY (location_id) REFERENCES locations(id)
);

CREATE INDEX idx_events_category_id ON events (category_id);
CREATE INDEX idx_events_initiator_id ON events (initiator_id);
CREATE INDEX idx_events_location_id ON events (location_id);

CREATE TABLE IF NOT EXISTS compilations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 0 MINVALUE 0) PRIMARY KEY,
    pinned          BOOLEAN NOT NULL,
    title           VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS compilation_events (
    compilation_id      BIGINT NOT NULL,
    event_id            BIGINT NOT NULL,
    CONSTRAINT fk_compilation_events_to_compilations FOREIGN KEY (compilation_id) REFERENCES compilations(id),
    CONSTRAINT fk_compilation_events_to_events FOREIGN KEY (event_id) REFERENCES events(id)
);